ALTER TABLE "User" ALTER COLUMN "studentId" DROP NOT NULL;
ALTER TABLE "UserSeasonProgress" ALTER COLUMN "studentId" DROP NOT NULL;
ALTER TABLE "UploadData" ALTER COLUMN "studentId" DROP NOT NULL;
ALTER TABLE "QuizAttempt" ALTER COLUMN "studentId" DROP NOT NULL;
ALTER TABLE "Quiz" ALTER COLUMN "studentId" DROP NOT NULL;
