import { maia } from "../database";

export class ContentEngine {

    /**
     * Extracts a detailed description from an educational image.
     * @param imageUrl The URL of the image/chart to analyze.
     * @returns The textual description generated by AI.
     */
    async extractDescription(imageUrl: string): Promise<string> {
        console.log(`[ContentEngine] Analyzing image: ${imageUrl}`);

        const systemPrompt = "You are an expert educational content analyst. Your task is to analyze educational materials (charts, diagrams, text pages) and provide a structured, detailed description.";

        const userPrompt = `Describe this educational material.
        Focus on:
        1. Context/Topic: What is the subject matter?
        2. Text Content: Extract key text visible.
        3. Visual Elements: Describe diagrams, charts, or illustrations.
        4. Key Concepts: What are the main learning points?
        
        Be concise but comprehensive.`;

        // Combine system instruction into the user prompt for models that might not strictly adhere to system role in vision,
        // or just rely on the 'analyzeImage' implementation which sends 'user' role messages.
        // For gemini/maia, sending strong context in the prompt is effective.

        const fullPrompt = `${systemPrompt}\n\n${userPrompt}`;

        try {
            const description = await maia.analyzeImage(fullPrompt, imageUrl);
            console.log('AI Response:', description);
            console.log(`[ContentEngine] Analysis complete. Length: ${description.length} chars.`);
            return description;
        } catch (error) {
            console.error('[ContentEngine] Extraction failed:', error);
            throw error;
        }
    }
}

export const contentEngine = new ContentEngine();
